# Autogenerated wrapper script for libversion_jll for i686-linux-musl-cxx03
export libversion, version_compare, version_sort

JLLWrappers.@generate_wrapper_header("libversion")
JLLWrappers.@declare_library_product(libversion, "libversion.so.1")
JLLWrappers.@declare_executable_product(version_compare)
JLLWrappers.@declare_executable_product(version_sort)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libversion,
        "lib/libversion.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        version_compare,
        "bin/version_compare",
    )

    JLLWrappers.@init_executable_product(
        version_sort,
        "bin/version_sort",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
