# Autogenerated wrapper script for libversion_jll for x86_64-w64-mingw32-cxx11
export libversion, version_compare, version_sort

JLLWrappers.@generate_wrapper_header("libversion")
JLLWrappers.@declare_library_product(libversion, "libversion.dll")
JLLWrappers.@declare_executable_product(version_compare)
JLLWrappers.@declare_executable_product(version_sort)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libversion,
        "bin\\libversion.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        version_compare,
        "bin\\version_compare.exe",
    )

    JLLWrappers.@init_executable_product(
        version_sort,
        "bin\\version_sort.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
